#define CONFIG_FILE_MAXSIZE				4096
#define PACKET_BUFFER_MAXSIZE			4096

#define DEVICE_CONFIG_FILE_MAXSIZE		1024
#define SWITCHSTATE_CONFIG_FILE_MAXSIZE	128
#define COUNTDOWN_CONFIG_FILE_MAXSIZE	1024
#define TIMING_CONFIG_FILE_MAXSIZE		4096



